### ISSUE TITLE
Can't find the bower executable on windows

### ISSUE THREAD

**Issue by meshelton** [mdedetrich/sbt-bower#3]
Running on windows generates this error:

[info] Pruning frontendDependencies
java.io.IOException: Cannot run program "bower" (in directory "C:\Users\Nathan\Meta\meta\src\main\resources\gui\www"): CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:388)
        at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:140)
        at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:171)
        at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:171)
        at sbt.BufferedLogger.buffer(BufferedLogger.scala:25)
        at sbt.AbstractProcessBuilder.runBuffered(ProcessImpl.scala:171)
        at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:168)
        at SbtBowerPlugin$$anonfun$pruneTask$1.apply(SbtBowerPlugin.scala:64)
        at SbtBowerPlugin$$anonfun$pruneTask$1.apply(SbtBowerPlugin.scala:60)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        at java.lang.ProcessBuilder.start(Unknown Source)
        at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:388)
        at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:140)
        at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:171)
        at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:171)
        at sbt.BufferedLogger.buffer(BufferedLogger.scala:25)
        at sbt.AbstractProcessBuilder.runBuffered(ProcessImpl.scala:171)
        at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:168)
        at SbtBowerPlugin$$anonfun$pruneTask$1.apply(SbtBowerPlugin.scala:64)
        at SbtBowerPlugin$$anonfun$pruneTask$1.apply(SbtBowerPlugin.scala:60)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error](*:update) java.io.IOException: Cannot run program "bower" (in directory "C:\Users\Nathan\Meta\meta\src\main\resources\gui\www"): CreateProcess error=2, The system cannot find the file specified

Using sbt version 13.5.

Looks like a quick and dirty fix would be to have the bower executable location be a setting key.

**Comment by mdedetrich** [comment]
I believe you need to add bower to your path for it to work in windows, can you verify that bower is in the windows path?

**Comment by gcarravi** [comment]
Did this issue get resolved? I am seeing the same even after including bower to the path.
thanks in advance

**Comment by gcarravi** [comment]
Actually I found the fix for this. If you are in windows you need to use:

task bower(type: Exec) {
    workingDir "${project.projectDir}/src/main/resources/webroot"
    commandLine "bower.cmd", "install", "--allow-root"
}

instead of:

task bower(type: Exec) {
    workingDir "${project.projectDir}/src/main/resources/webroot"
    commandLine "bower", "install", "--allow-root"
}

hope it helps!
